## 배열의 연결
* 행의 수나 열의 수가 같은 두 개 이상의 배열 합침(결함) -> 더큰 배열-> shape가변함 -> dtype 같음
* concatenate: 리스트의 합, 곱 연산 -> 합치거나 복사/ 배열? : 벡터화 연산-> + * 변형 x



In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)
# arr1 : np.array([[1, 2], [3, 4]])
# arr2 : np.array([[5, 6], [7, 8]])

In [3]:
np.concatenate([arr1, arr2])
# 1차원 배열 : 행이 하나인 2차원 배열
# 2차원 배열 : 행이나 열이 같아야 한다

array([1, 2, 3, 4, 5, 6])

In [22]:
a= np.concatenate([arr1, arr2], axis=0) # axis=0
a
# 행을 기준으로 한다
# -> 가로 방향으로 붙여준다
# -> 열의 갯수가 늘어난다


array([1, 2, 3, 4, 5, 6])

In [41]:
np.concatenate([arr1, arr2], axis=1)
# 열을 기준으로 한다
# -> 세로 방향으로 붙여준다
# -> 행의 갯수가 늘어난다
'''
array([[1, 2, 5, 6],
       [3, 4, 7, 8]])
'''

AxisError: axis 1 is out of bounds for array of dimension 1

hstack vstack : 수평(horizontal), 수직(vertical)

In [27]:
a1 = np.array([[1, 1, 1],[1., 1., 1.]]) #-> 2x3

In [29]:
a2 = np.array([[0., 0.], [0., 0.]])# -> 2x2
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

vstack : 열의 수가 같은 두 개 이상의 배열을 위아래로 연결 → 행의 수가 커진다

In [15]:
b1 = np.array([[1., 1., 1.],
        [1., 1., 1.]]) # 2 x 3
b2 = np.array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) # 3 x 3

In [16]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

dstack : 행이나 열이 아닌 깊이(제3의 축) 방향으로 배열을 합쳐줌 → 가장 안쪽의 원소의 차원이 증가
행, 열, 깊이배열 두 개가 겹치므로 합치고자 하는 배열들의 크기가 모두 같아야 함

In [12]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))

In [13]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

`stack` : dstack과 달리  마지막 차원이 아니라 지정한 차원(축)으로 배열을 연결 → 배열 두 개가 겹치므로 합치고자 하는 배열들의 크기가 모두 같아야 함

## 인덱서(indexer)
* 소괄호(`()`)를 사용하는 게 아니라 대괄호(`[]`)를 사용해서 작동하는 특수한 메소드
* `np.r_`: hstack과 유사
* `np_c_`: dstack과 유사
<br>
* np.tile(arr, n 또는 (shape)) : 반복할 배열, 반복할 모양(횟수) → 그대로 배열을 반복해서 채워줌

## 배열의 연산
* 브로드캐스팅
    * Numpy에서 지원하는 기능
    * 모양이 다른 행렬간의 연산 x -> Numpy에서는 행이나 열이 일치하거나 하면 알아서 확장시켜서 
    처리해주는 기능(자연수 -> 1차원 배열, 2차원 배열 모양에 맞춰서 확장 -> 계산)
    * 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춤
* 차원 축소 연산
    * 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고, 각 행에 처리된 연산으로 한 차원 낮은 벡터를 구성하게 하는 연산 → 한 행을 통계 수치로 축소해줌
    * **axis=0**인 경우에는 열 연산, axis=1인 경우는 행 연산 → 기준이 되는 열을 정해주는 게 axis고, 기준이 되는 축은 갯수의 변경
    * axis 인수는 대부분의 차원 축소 명령에 적용할 수 있음
    * **axis=0**인 경우에는 열 연산 → 행의 개수가 유지
    * **axis=1**인 경우는 행 연산 → 열의 개수가 유지
    * axis 인수는 대부분의 차원 축소 명령에 적용할 수 있음

In [31]:
y = np.array([[1,1,1],[2,2,2]])
y

array([[1, 1, 1],
       [2, 2, 2]])

In [32]:
y.sum(axis=0)

array([3, 3, 3])

In [33]:
y.sum(axis=1)

array([3, 6])

## 정렬
* `np.sort` : 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열 생성
* 2차원 이상인 경우 -> 행이나 열을 따로따로 정렬
    - 어느 차원으로 계산을 할지 axis 인수를 사용해서 지시
    - **axis=0**인 경우에는 열 연산 → 행의 개수가 유지
    - **axis=1**인 경우는 행 연산 → 열의 개수가 유지
    - axis 인수는 대부분의 차원 축소 명령에 적용할 수 있음

In [38]:
a = np.arange(1,13).reshape(4,3)

In [39]:
np.sort(a,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
np.sort(a,axis=1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

* `arr.sort` : in-place 메소드 → 원본에게 영향을 줌 (arr.copy) → np.sort를 쓰는 걸 추천
*`np.argsort` : 정렬된 값 → 정렬 했을 때의 인덱스들 
    1. 정수 배열 인덱스
    2. 행을 기준으로 정렬 시키고 싶을 때 arr[:,np.argsort(arr[1])] → 2번째 행의 크기에 따라서 나머지 행들까지 정렬

## 기술 통계 (descriptive statstics)
* 데이터의 특징을 나타내기 위해서 통계적인 값들을 사용하는 것
* 데이터 집합에 대해 통계를 계산
* 데이터 개수 : `len(x)`
* 평균 : `np.mean(x)`
* 분산 : `np.var(arr)`
* 최댓값, 최솟값 : `np.max(arr)` `np.min(arr)`
* 중앙값 : `np.median(arr)` -> 데이터의 수가 짝수면, 중앙값은 맨 중앙의 값 2개의 평균
* 사분위수 : `np.precoentile(arr, 백분위수)`

## 난수 발생과 카운트
* 시드 설정 : (난수 설정을 할 때)일치된 결과를 얻고 싶다면 (과제나 학습에서) `np.random,seed` 시작하는 난수의 코드를 입력해주면 해당 코드를 기반으로 나숫가 설정되기 때문에 예측가능(ML random_state)
* `np.random.rand`: 0과 1사이
    * np.random.rand(갯수)
* `np.random.shuffle`: 특정 배열의 내부 원소 순서를 섞어줌
* `np.random,choice(arr, size, replace, p)`
    * size : 정수 값, shape
    * replace : T/F -> 복원/비복원 추출(중복/비중복)
    * p : arr의 크기만틈 배열 -> 특정 항목에 확률 가중치를 얼마나 둘 것이냐?
*`np.random,randn`: 평균(기댓값)이 0이고 표준편차가 1인 표준 정규분포를 따르는 난수 생성 -> 통계적으로 자주 쓰이는 난수 분포를 만들어 주겠다.
*`np.random.randint` : 임의의 범위의 숫자들을 리턴 ** 자주 사용**
    * low, high, size
    * low : 0~low(제외)
    * low, high : low~high(제외)
    * size → size 갯수, shape면 해당 모양으로
* `np.unique`
    * np.unique(arr) : arr의 중복되지 않은 고유값 행렬
    * np.unique(arr, return_counts=True) : 고유값 + 갯수